# UI: Grafana http://localhost:3000 (admin/admin)
services:
  # OpenTelemetry Collector: single OTLP endpoint, fans out to Tempo + Loki
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.112.0
    command: ["--config=/etc/otel/config.yaml"]
    volumes:
      - ./test/tracing/otel-collector-config.yaml:/etc/otel/config.yaml:ro
    ports:
      - "4317:4317"   # OTLP gRPC
      - "4318:4318"   # OTLP HTTP
    healthcheck:
      test: ["CMD", "/otelcol-contrib", "--version"]
      interval: 5s
      timeout: 2s
      retries: 20
      start_period: 5s
    depends_on:
      tempo:
        condition: service_healthy
      loki:
        condition: service_healthy

  dmt:
    environment: &otlp_enabled
      OTEL_TRACES_EXPORTER: otlp
      OTEL_LOGS_EXPORTER: otlp
      OTEL_TRACES_SAMPLER: parentbased_always_off
      OTEL_EXPORTER_OTLP_PROTOCOL: http_protobuf
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4318
      OTEL_EXPORTER_OTLP_LOGS_ENDPOINT: http://otel-collector:4318/v1/logs
      OTEL_SERVICE_NAME: dmt

  testrunner:
    environment:
      <<: *otlp_enabled
      OTEL_SERVICE_NAME: limiter
      OTEL_TRACES_SAMPLER: parentbased_always_on
    depends_on:
      dmt:
        condition: service_healthy
      liminator:
        condition: service_healthy
      otel-collector:
        condition: service_healthy
      grafana:
        condition: service_started

  tempo:
    image: grafana/tempo:2.6.1
    command: ["-config.file=/etc/tempo.yaml"]
    volumes:
      - ./test/tracing/tempo.yaml:/etc/tempo.yaml:ro
    ports:
      - 3200:3200
    healthcheck:
      test: ["CMD-SHELL", "wget -q -O- http://localhost:3200/ready || exit 1"]
      interval: 5s
      timeout: 2s
      retries: 20
      start_period: 5s

  loki:
    image: grafana/loki:3.1.1
    command: ["-config.file=/etc/loki/config.yaml"]
    volumes:
      - ./test/tracing/loki.yaml:/etc/loki/config.yaml:ro
    ports:
      - 3100:3100
    healthcheck:
      test: ["CMD-SHELL", "wget -q -O- http://localhost:3100/ready || exit 1"]
      interval: 5s
      timeout: 2s
      retries: 20
      start_period: 5s

  grafana:
    image: grafana/grafana:12.3.3
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - ./test/tracing/grafana/provisioning:/etc/grafana/provisioning:ro
    ports:
      - 3000:3000
    depends_on:
      loki:
        condition: service_healthy
      tempo:
        condition: service_healthy
